### ISSUE TITLE
[Feature Request] List of all enrolled course

### ISSUE THREAD

**Issue by RuthlessRuler** [r0oth3x49/udemy-dl#134]
I would like to request this feature of listing all the course the account is enrolled in,

**Comment by r0oth3x49** [comment]
@RuthlessRuler its easy to watch your courses through web rather than watching it on command line. so for now i 'm not considering this as feature but may be in future releases. BTW thanks for your suggestion.

**Comment by RuthlessRuler** [comment]
Well it's difficult to see the whole list if you have 200+ Enrolled courses on Udemy.

**Comment by r0oth3x49** [comment]
exactly udemy API returns the same result in request as well. so currently there is no way to put a single request and get the list of all courses which means if i implement this feature on command line, this wont help as well because the list will be shown as chunk instead complete list until unless you have less then 99 courses in your account.
