### ISSUE TITLE
a couple of issues

### ISSUE THREAD

**Issue by bamacanuck** [r0oth3x49/udemy-dl#205]
I was going to write about one issue, and then encountered a second.

I have failed to use the udemy-dl utility correctly, in the past. In these most recent cases, however, I'm confident I've used it in the same manner that led to successful results, as recently as a couple of weeks ago.

The first bit of trouble I mean to explain, I first encountered just yesterday. Using the utility, it seems the system allowed proper login, and even acknowledged the existence of chapters/sections of the chosen course, but was unable to find any of its (video file) lectures.

This other problem, which I've just encountered today (so far), seems to disallow login (through the udemy-dl utility). The response I receive is as follows.

"Unable to extract login-form form"

I hope you can help.

I thank you again, for creating and maintaining this wonderful tool.

==========================================================

Here are some additional details, which may help with "diagnosis."

The command I employed for some of these attempts was as follows.

python udemy-dl.py https://www.udemy.com/the-complete-javascript-course/

This yielded the usual login process. In some cases, this led to a failure, with that message I noted earlier ("Unable to extract login-form form"). In other cases, as with my most recent attempt, the utility succeeded through the login process, and then noted the correct chapters/sections of the course (numbers, and associated chapter headings, such as "Chapter (05 Advanced JavaScript Objects and Functions)"), and even noted the start of downloading for each chapter/sections, but - in all cases - also noted that these chapters/sections were essentially empty (using the phrase "Found (0) lectures ...").

Again, I thank you for your time.

**Comment by r0oth3x49** [comment]
@bamacanuck 1st of all thanks for the detailed explanation about the issue you are facing. as of now you are facing two issues.
 - unable to login. (for which i would suggest take a look at issue #184 where it is discussed in detail)
 - Chapters without lectures. (this was fixed in #179 . you should clone the latest `master` to verify)

One more request, i appreciate the way you explained the issues you are facing but still i would recommend, take a look at [issue reporting guideline](https://github.com/r0oth3x49/udemy-dl#issue-reporting-guideline). do check twice if you are facing the issues with most recent commit added to the `master` and whether or not its been reported and fixed.
