### ISSUE TITLE
pdf / quizzes

### ISSUE THREAD

**Issue by selanium** [r0oth3x49/udemy-dl#21]
as the topic **pdf / quizzes** are **not** detected with this program, so we can download non of these files

**Comment by r0oth3x49** [comment]
@selanium quizzes are out of scope if you buy a course videos and other material are enough for learning quizzes can be taken on the basis of your learning that's why i haven't included the download of quizzes so i 'm closing this issue. for other files such as PDF and other i 'll w8 for more reports.
