### ISSUE TITLE
Suntitle file & some files not downloading

### ISSUE THREAD

**Issue by Aqsa97** [r0oth3x49/udemy-dl#25]
So the script works perfectly fine but for some later lectures it doesn't download the subtitle files. It shows an error that's like "URL ERROR: HTTP Error 403: Forbidden"

I guess it isn't your fault as it downloaded the earlier subs but do you have any idea how can I fix this problem? 

Also, I noticed how the script would skip some files from the course. It downloads videos, subs, PDF, zipped & txt files perfectly fine. But it skips over some files. You can see the files it skips here - http://prntscr.com/hefx3z

**Comment by Aqsa97** [comment]
I jus encountered another issue. The script won't download the last 20 video files and shows an error " URL ERROR: HTTP Error 401: Forbidden"

This is a paid course which I have purchased. I don't know why this happens..

**Comment by Chlitzxer** [comment]
> @Aqsa97 I believe those files that you mentioned on the screenshot are "html" I used to use another script months ago that was custom made and when the format "html was added" it used to grab those as well.

**Comment by r0oth3x49** [comment]
@Aqsa97 thanks for the report.
**URL ERROR: HTTP Error 403: Forbidden for subtitle**
you are facing this error because the subtitles direct download links expires earlier so i would suggest to download the whole course first by using `--skip-sub` if the course is large, this option which will skip the subtitles and download the whole course. and then after downloading course you can then download subtitles only with another option `--sub-only`. and i will take a look on that skipping part of the course.

**URL ERROR: HTTP Error 401: Forbidden means now you are not authorized to download with current session you have to refresh your session (so simply rerun the script against the same course)**
this is causing just because you are downloading a large course and your current session expires for that direct download links. reason might be your internet speed your internet speed is not enough to download the whole course in one session and udemy simply resets the current session i will add a proper handle for this error as well. for now the fix you can run the script again to download the course.

**Comment by Aqsa97** [comment]
Ohhh I see. Okay I'll try downloading the subtitles the way you mentioned. Thank you! :)

And I'm downloading Web Developer Bootcamp by Colt Steele:
https://www.udemy.com/the-web-developer-bootcamp/

Yes the course is very large but I have tried running the script 4 times now, and each time it stops downloading the last few files. If you could add feature where I could start from middle (any point, other than the start) of the course, that'd be really helpful.

**Comment by r0oth3x49** [comment]
@Aqsa97 the reason i didn't added feature for start downloading from some user define point is because **udemy-dl** by default resumes from the same point where it left off. about skipping part i will have a look  and add a fix for that ASAP.

**Comment by Aqsa97** [comment]
Thank you for the HTML file update :)

I guess I have to try downloading it again.. btw do you know how long does one session last? 
Also, I did check but udemy-dl doesn't resume from where it left off like you said. It always starts from the beginning.

**Comment by r0oth3x49** [comment]
@Aqsa97 i have tried it always download from the point where it left off.
**POC**
![untitled](https://user-images.githubusercontent.com/11024397/33802241-7e2419de-dd94-11e7-9b5b-795d6e6336c0.png)
