### ISSUE TITLE
Missing percentage completed for entire course

### ISSUE THREAD

**Issue by soumendrak** [r0oth3x49/udemy-dl#251]
Currently, the percentage completion for each chapter/video is there.
Need a statistics in the terminal which says the percentage completion of the entire course.

**Comment by r0oth3x49** [comment]
@soumendrak udemy-dl downloads single course at a time, so how can i show the % complete of course? i 'm not getting what you actually want to do, need a bit explanation.

**Comment by r0oth3x49** [comment]
@soumendrak but i think `udemy-dl` already have status for the course in form of chapter(s) number.

![capture](https://user-images.githubusercontent.com/11024397/42553260-96f242b2-84f9-11e8-92d1-84e544fd943f.PNG)

with the above status user can easily identity how much course is so far downloaded. but i would love to see your method if that seems good to me i will mark this as future enhancement otherwise i don't see any issue if don't add this % kind of thing on course because user is already being notified with the chapter(s) number current in process.

**Comment by soumendrak** [comment]
@r0oth3x49 , yeah I agree with you on the chapter status. It is helpful if the courses are small. However, if we see the following scenario ([a long course](https://wipro.udemy.com/advanced-plc-programming/learn/v4/) download screenshot)
![udemy_download_](https://user-images.githubusercontent.com/10120538/42553969-abd9570e-8500-11e8-97c7-ade36d9ceb45.PNG)

Here I agree, We can know which chapter is getting downloaded. However, it is hard to know the downloaded lecture belong to which chapter/section without scrolling top (which is hard).  
Therefore, I suggest we should have a course download status at the bottom or somewhere which is easier to look.

**Comment by r0oth3x49** [comment]
@soumendrak there is one more way you can check is to directly open the course folder and check how many chapters are done and which one is currently in downloading status. i will wait for others suggestions as well for now i 'm closing this issue as others suggestion required.
