### ISSUE TITLE
Unable to extract login-form form

### ISSUE THREAD

**Issue by thoriqnf** [r0oth3x49/udemy-dl#278]
Good day,

Receiving the following error on macbook pro,
before this everything normal and 1 start download new courses. My laptop restart when I almost finished and after that i tried using same script and this error message comes

Unable to extract login-form form

i already try clong new repo but still didn't work

**Comment by r0oth3x49** [comment]
@thoriqnf please follow issue reporting guieline, this issue is discussed so many times take a look at #184

**Comment by nokillkenny** [comment]
Hello,
I am not sure the exact repro steps, but I believe it happens when the app is disconnected and the user retries to login manually. I see this message more when I try to reconnect.

The workaround for me is to disconnect my internet and get another IP. This seems to get a new session and I see the message less.

I hope this helps!

**Comment by nokillkenny** [comment]
I've uploaded a screenshot that gives clues into the behavior. The first attempt crashed, so I retried again and received a weird message upon retrieving the course list.

The second attempt shows the login error.

Before the third attempt, I shut down my router and got a new dynamic ip, which let me download. If I were to guess the fix it would be to invalidate the session or clear the login cache.

https://i.imgur.com/yGXugYL.png
