### ISSUE TITLE
 help me 

### ISSUE THREAD

**Issue by yeguangteng** [r0oth3x49/udemy-dl#307]
udemy says : 403 Forbidden  retry after few minutes...

not download ???? help me

**Comment by dillagr** [comment]
you will need to update to the latest version (git pull). this has been resolved.

**Comment by naveenkg29** [comment]
I got this error, Help me please

requests.exceptions.SSLError: HTTPSConnectionPool(host='www.udemy.com', port=443): Max retries exceeded with url: /api-2.0/auth/udemy-auth/login/?fields[user]=access_token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by r0oth3x49** [comment]
@naveenkg29 you have to wait for some time. of update your packages. the error is specific to library not udemy-dl.
