### ISSUE TITLE
How to pre-define the course URL in Array as well as Username and password in the script?

### ISSUE THREAD

**Issue by nandanosql** [r0oth3x49/udemy-dl#322]
Hi,
I just want to make few changes into the source code to make it more user friendly.

I want to : - 
1. pre-define my email and password so I don't want to enter the email and password again and again
2. Enter all URL in form of queue so all courses will download one by one in back to back format.

Please tell me how to make changes and make it more use-able.

Thanks.

**Comment by r0oth3x49** [comment]
> 1. pre-define my email and password so I don't want to enter the email and password again and again.

@nandanosql there is switch `--cache` you can use.
when you specify your creds on terminal it will create a `configuration` and save your `email`, `password`, `quality` request for video(s) and the `path` where you want to download the course(s). this is also specified in a `README` file take a look at that, I have created that for users so that they can explore what the tool offers.

> 2. Enter all URL in form of queue so all courses will download one by one in back to back format.

i will consider this as future enhancement. currently there is no option. 

By the way don't be so lazy 😉.

**Comment by teamcrisis** [comment]
I see this marked as closed.

> Enter all URL in form of queue so all courses will download one by one in back to back format.

Was ever added as a feature? This would be a very useful, especially when needing to update many courses
