### ISSUE TITLE
all courses in my account at once ?

### ISSUE THREAD

**Issue by B4GP4CK** [r0oth3x49/udemy-dl#33]
Bro can i download all courses which i bought at once ?? need help

**Comment by r0oth3x49** [comment]
@B4GP4CK you cannot download all the courses at once with this script until you create an automation to run the script against a list of courses.
**Windows.**
you can create a batch file which will automate task for you.
**Unix**
either you can use `for` or `while` loop on terminal or create a bash program that automates the download for you..

**Comment by soumendrak** [comment]
@r0oth3x49 , could you please add this batch download script to the repository for the public? It will be very helpful.

**Comment by CMMT20** [comment]
hello, here you have the script to loop udemy-dl through all your courses, so downloading multiple course in once command:
Shell script to loop udemy-dl through all your courses, you download all with only one script
This works in macOS
Much of you already know how to do this, but for people like me who didn't

**To Reproduce: copy paste this en terminal 
- of course prompt placed in in the directory  udemy-dl-master, in my case
/Users/myuser/PycharmProjects/udemy-dl-master
- change urls to yours, here i put some of them like example**
- finally, this is the script:

array=( https://www.udemy.com/course/react-redux https://www.udemy.com/course/react-the-complete-guide-incl-redux https://www.udemy.com/course/result-oriented-web-developer-course https://www.udemy.com/course/sql-and-postgresql-for-beginners https://www.udemy.com/course/sql-mysql-for-data-analytics-and-business-intelligence https://www.udemy.com/course/statistics-for-data-science-and-business-analysis https://www.udemy.com/course/the-complete-app-design-course-ux-and-ui-design https://www.udemy.com/course/the-complete-crowdfunding-course-for-kickstarter-indiegogo https://www.udemy.com/course/the-complete-javascript-course https://www.udemy.com/course/the-complete-junior-to-senior-web-developer-roadmap https://www.udemy.com/course/the-complete-ruby-on-rails-developer-course https://www.udemy.com/course/the-complete-sql-bootcamp https://www.udemy.com/course/the-complete-web-developer-course-2 https://www.udemy.com/course/the-complete-web-developer-zero-to-mastery https://www.udemy.com/course/the-complete-wordpress-website-business-course https://www.udemy.com/course/the-ultimate-google-adwords-training-course https://www.udemy.com/course/the-ultimate-mysql-bootcamp-go-from-sql-beginner-to-expert https://www.udemy.com/course/ultimate-guide-to-ux https://www.udemy.com/course/understand-javascript https://www.udemy.com/course/wordpress-academy-2018-beginners-crash-course https://www.udemy.com/course/wordpress-multi-vendor-marketplace-ecommerce-website )

for u in "${array[@]}"
do
    python udemy-dl.py "$u"
		
done



**Expected behavior**
This little script loop udemy-dl through the list of course you put in the array
And download the content of all of them.

**Screenshots**

**Python Environment (please complete the following information):**
 - OS Platform: macOS bigSur
 - Python Version 3.8.5

**Additional context**

**Comment by CMMT20** [comment]
Thanks r0oth3x49 for creating and sharing, it is a great tool, i use it a lot. Greetings from Spain.

**Comment by CMMT20** [comment]
pd i don't know why but this editor don't conserve indentation.
Of course the loop action must be indented
for u in "${array[@]}"
do
    python udemy-dl.py "$u"

done
