### ISSUE TITLE
URLError : either your internet connection is not working or server aborted the request

### ISSUE THREAD

**Issue by sayemsarkar123** [r0oth3x49/udemy-dl#352]
![Screenshot_1](https://user-images.githubusercontent.com/20737377/54851024-e77d2800-4d12-11e9-8754-508984ae0bc9.png)

Bro, see this it's work with cookies but one problem here it's just  download videos. cann't download subtitle. iam try with many times with different courses. it's show me the same problem.

**Comment by Eugenio-Liso** [comment]
Hi,

i have the same problem with those subtitles. The strange thing is: if you run again the script, there is a possibility that the subtitle is actually downloaded. So i assume there's a problem server side. 
The tool does not try to download it again, through a "retry" mechanism...for this kind of problem, it would be a very nice feature. I didn't find it in the README.

**Comment by r0oth3x49** [comment]
@Eugenio-Liso the reason i did not added the retry mechanism is because if direct links to those subtitles expires then if you retry thousand times it would be just a burden on server and still you will not be able to download. Adding retry mechanism is a good feature but in that case i have to refresh the auth session which mean fetching again all the links.

@sayemsarkar123 this is a handle to an exception so that the code don't break and continues to download what can be downloaded.

**Comment by sayemsarkar123** [comment]
@r0oth3x49 bro after download the whole course iam again run the same command but it's failed to download subtiles but in sometimes it's download 1 or 2 subtiles each chapter. so it's means i need to run same command again and again for download subtitle. please solve this isssue.

**Comment by r0oth3x49** [comment]
@sayemsarkar123 you can send me the details on my email `nasir251292@gmail.com` with your credentials if you are okay with sharing. so that i can reproduce and fix.

**Comment by sayemsarkar123** [comment]
@r0oth3x49 Bro, please check your e-mail

**Comment by brundidge** [comment]
Download subtitles is back. No more URLError (ಥ﹏ಥ)

![a](https://user-images.githubusercontent.com/48912654/54966327-d2e79c80-4f6b-11e9-9ed2-499458a782e9.gif)
