### ISSUE TITLE
Duplicate a lot of files when using --unsafe option

### ISSUE THREAD

**Issue by brundidge** [r0oth3x49/udemy-dl#384]
OS: Windows 10 1809
Python: 2.7.16 (even Python 3 if doing the same)
Course: https://www.udemy.com/professional-rails-5-development-course/

Assuming that i'm a newbie here, i use this tool and i completed download my course (using -u -p only because i'm a newbie, who know what on earth other options are about and why i should care about it)

The next day i noticed that i have a blank text file? WTF? What should i do? I open a new issue of course. @r0oth3x49 or someone come in and says: "Hey dude, --unsafe should fix your problem"

OK, i go and add --unsafe to "fix" the problem. And wow, it's just a txt file, why it takes so long. Turn out it downloads again whatever i have files that are not in it "original" name. And more worst than that, i have a folder with a "+" sign in it, so i have to download the whole folder again. In this case the folder size 200MB, and other random files have been downloaded again and duplicate in all over places.

![a](https://user-images.githubusercontent.com/48912654/56947489-e2cf3f00-6b1c-11e9-9db3-02235cd07154.png)

**Comment by r0oth3x49** [comment]
@brundidge its a common thing bro, when i say use `--unsafe` switch it means i 'm not sanitizing any title/name given by udemy API for a course content, that's why everything is inside title and when you don't use `--unsafe` switch, the code sanitize each title/name. so i 'm closing this as invalid. Before creating an issue take a look at readme again.

# Download lectures containing unsafe unicode characters in title/name (option: --unsafe).

the above thing explains that the purpose of this flag is not to sanitize the name and use as it is.
