### ISSUE TITLE
Downloads keep stopping.

### ISSUE THREAD

**Issue by Puyodead1** [r0oth3x49/udemy-dl#411]
![image](https://user-images.githubusercontent.com/14828766/60844561-a0bf1b00-a1a7-11e9-9285-e1d014566c54.png)
After i start the download, it stops after some time.

**Comment by brandongalbraith** [comment]
@Puyodead1 https://github.com/r0oth3x49/udemy-dl#issue-reporting-guideline

**Comment by Puyodead1** [comment]
Enviroment: Windows 10 x64 1903, Python 3.7.3
Course URLS: https://www.udemy.com/unrealvr/, https://www.udemy.com/unrealcourse/
Command Used: python udemy-dl.py <course url> -k cookie.txt -q 720 --skip-sub

Steps:
  - Start a download
  - Wait for a little bit
  - check back and the downloads appear to hang
  - use taskmanager to kill the python process (under Windows Command Processor)
  - run the command again

**Comment by r0oth3x49** [comment]
i will try to reproduce & fix ASAP hopefully this weekend .

**Comment by iZero7** [comment]
this might be due to windows bugged terminal, try disabling quick edit mode and insert mode from its settings

**Comment by Puyodead1** [comment]
> this might be due to windows bugged terminal, try disabling quick edit mode and insert mode from its settings

Okay, i'll try this

**Comment by salytwo** [comment]
I have using this application with win 7 and course url is https://www.udemy.com/machine-safety-leadership/
command : udemy-dl.py  https://www.udemy.com/machine-safety-leadership/
but the problem was some lectures do not downloaded fully. it keep jumping to next lecture while the current still not completed, sometimes at 10% percentage while others 80%...etc
other cases also complete lectures.
the internet connection is stable no losses.
I tried to start again but it check files name existence so it assume the lecture is fully downloaded while this is not the case as explained above.

I tried to get links only using your software then I used another like IDM or Jdwnloader but the problem is files names is randomly characters.

I appreciate your efforts well and hope to solve this small issue.

**Comment by jiaqiang125** [comment]
> I have using this application with win 7 and course url is https://www.udemy.com/machine-safety-leadership/
> command : udemy-dl.py https://www.udemy.com/machine-safety-leadership/
> but the problem was some lectures do not downloaded fully. it keep jumping to next lecture while the current still not completed, sometimes at 10% percentage while others 80%...etc
> other cases also complete lectures.
> the internet connection is stable no losses.
> I tried to start again but it check files name existence so it assume the lecture is fully downloaded while this is not the case as explained above.
> 
> I tried to get links only using your software then I used another like IDM or Jdwnloader but the problem is files names is randomly characters.
> 
> I appreciate your efforts well and hope to solve this small issue.

+1, I have the same issue that some lectures do not downloaded fully and stoped sometimes.

**Comment by wkremser** [comment]
hi, i am having the same issues. it seems that if there are "hickups" on the internet connection, this is handled badly .. sometimes the download get stuck, other times i get stack traces and the process stops. for me it happens only at the videos, never at subtitles. 

i can attach stack traces when i run the next downloads.
