### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by davidonlaptop** [r0oth3x49/udemy-dl#44]
I indeed have access to the internet...

sudo python udemy-dl.py -u my@email.com -p thepassword https://www.udemy.com/capital-market-immersion -l
[*] : Downloading webpage..
[*] : Extracting course information..
[*] : Downloading 'capital market immersion'.
[*] : Trying to login as (davidonlaptop@gmail.com)...
[-] : Connection error : make sure your internet connection is working.

**Comment by r0oth3x49** [comment]
@davidonlaptop you should see this [Issue 16:Connection error](https://github.com/r0oth3x49/udemy-dl/issues/16)
if you are on Mac or unix based machine you should upgrade `requests` package for Python2 and also install `requests[security]` to make it work its mention in **README** as well.

**Comment by davidonlaptop** [comment]
I see... Getting a weird error when installing requests[security] :

> OSError: [Errno 1] Operation not permitted: '/tmp/pip-e2gWWZ-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pyOpenSSL-0.13.1-py2.7.egg-info'

Does udemy-dl downloads the course attachments too (pdf, etc.) ?

**Comment by r0oth3x49** [comment]
yes it downloads the attachments etc and this error is cause by OS and particular to `requests` you can see if the patch here given works for you.
- [requests issue 3883](https://github.com/requests/requests/issues/3883)
- [requests issue 3189](https://github.com/requests/requests/issues/3189)
 otherwise download the latest Python version and install then try downloading all the libs by using `sudo pip install -r requirements.txt --upgrade`

**Comment by davidonlaptop** [comment]
> yes it downloads the attachments etc
sweet!

The patch from the links didn't work but python3 did it:

```
sudo -H pip3 install requests[security]
sudo -H pip3 install -r requirements.txt
python3 -u email@gmail.com -p password https://www.udemy.com/capital-market-immersion -l
```
Thanks!
