### ISSUE TITLE
resume/reconnect/retry till its complete

### ISSUE THREAD

**Issue by Nightreaver** [r0oth3x49/udemy-dl#449]
If there the possibility to get some kind of resume/reconnect/retry feature till download is completed?
Obviously the udemy cdn is awful so im trying to download it to enjoy without buttering but it seem even this download cannot get past the timeouts... after roughly 2mb, the download get stuck and skipped

```
[*] : Lecture(s) : (4 of 12)
[*] : Downloading (004 Angular vs Angular 2 vs Angular 8)
[*] : 7.01MB/1.55MB 22.11% |#######-----------------------| 26.80kB/s eta 03:28s[*] : Lecture : '004 Angular vs Angular 2 vs Angular 8' (download skipped).
[-] : Reason : HTTPSConnectionPool(host='a.udemycdn.com', port=443): Read timed out.

[*] : Lecture(s) : (6 of 12)
[*] : Downloading (006 Project Setup and First App)
[*] : 42.84MB/1.98MB 4.62% |#-----------------------------| 19.65kB/s eta 35:29s[*] : Lecture : '006 Project Setup and First App' (download skipped).
[-] : Reason : HTTPSConnectionPool(host='a.udemycdn.com', port=443): Read timed out.

[*] : Lecture(s) : (7 of 12)
[*] : Downloading (007 Editing the First App)
[*] : 94.18MB/3.08MB 3.27% |#-----------------------------| 25.43kB/s eta 01:01:07s[*] : Lecture : '007 Editing the First App' (download skipped).
[-] : Reason : HTTPSConnectionPool(host='a.udemycdn.com', port=443): Read timed out.
```

and so on... 

should i just relaunch the download till it succeeds or what is the preferred way to do?
I cannot find any option for this issue.

**Comment by r0oth3x49** [comment]
hmm need to check speed seems too slow

**Comment by r0oth3x49** [comment]
I 'm closing this issue as won't resolve, may be in future i check for the fix.

**Comment by SirGouki** [comment]
A retry argument or default functionality would be very useful.  I'm trying to download a course right now because my bandwidth cap has been hit and I'm capped at 80KBps, so streaming the course is not viable.  I keep occasionally getting errors that the connection timed out, and it just goes to the next lecture.  If I ctrl + C it out, and restart it, the download does resume, but I'd like to be able to walk away and not have to worry about it skipping files that aren't done like this.

**Comment by r0oth3x49** [comment]
@SirGouki as i said i will take a look at this in future versions but not for now.
