### ISSUE TITLE
Udemy-dl ignores the -q switch

### ISSUE THREAD

**Issue by scmm-stack** [r0oth3x49/udemy-dl#457]
**Describe the bug**
I specify the desired resolution with -q 1080 switch but the downloader saves only 720.

**To Reproduce**
1. udemy course url: https://www.udemy.com/course/amazon-eks-starter-kubernetes-on-aws/
2. python udemy-dl.py https://www.udemy.com/course/amazon-eks-starter-kubernetes-on-aws/ -q 1080 -k acs.txt

**Expected behavior**
The downloaded video should be in 1080 resolution. If you watch online on udemy you can switch bretween 144p, 360p, 480p and 720p but if you set the quality to auto you get 1080p (depending on the connection).

**Screenshots**

**Python Environment (please complete the following information):**
 - Windows 10
 - Python 3.8.0

**Comment by r0oth3x49** [comment]
@scmm-stack this is not an issue because currently their is no support to download hls stream based videos and udemy provides maximum mp4 quality 720p while 1080p is in hls.

so currently there is no way you can download hls based stream.

'm closing the issue as duplicate as this is already discussed and set for future enhancement.
