### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by chukked** [r0oth3x49/udemy-dl#539]
just now, i used both the methods

-u username -p password
and
cookie

but both are returning 403 Forbidden
is it not possible to download the course anymore at all as they are invalidating the request all together

[*] : Trying to login using cookies ...
[+] : Logged in successfully.
[-] : Udemy Says : 403 Forbidden You should use cookie base method to authenticate or try again in few minutes ...

**Comment by xd003** [comment]
Try this
1) Log out of your udemy and log in again
2) Now copy the fresh token and replace it in the cookie.txt file
now it should work

i too had faced this issue once where it gave 403 error with cookies but using a fresh cookie -access token worked well

**Comment by r0oth3x49** [comment]
@chukked you should update the cookies instead or access token

**Comment by chukked** [comment]
thank you, it is working now :)

**Comment by xd003** [comment]
@r0oth3x49 i have 2 suggestions

1) Since login through username and password is now depreciated , you should remove the -u and -p flags from readme and mention clearly that only cookies login is supported ( because new users might not know only 1 method works , so they may create issue after trying -u,-p authentication )

2) Even if someone uses cookies , there is chance that they may get error 403 Forbidden... , so you can mention these steps in readme - https://github.com/r0oth3x49/udemy-dl/issues/539#issuecomment-663841172 . 

Then anyone wont report authentication related issues and only other real issues will get reported
