### ISSUE TITLE
want to stop text about log

### ISSUE THREAD

**Issue by jaan143** [r0oth3x49/udemy-dl#585]
hello
i dont want to get course log file which is containing (udemy-dl.text) file inside course folder
so did any command here to skip this file ?

**Comment by r0oth3x49** [comment]
you mean udemy-dl.conf or udemy-dl.log? your question is not clear enough.

**Comment by jaan143** [comment]
@r0oth3x49  when i download any course i got a file which name is "udemy-dl" it is text file which is outside from section folders 
i dont want to get this file

**Comment by r0oth3x49** [comment]
hmm that's log file which is if any sort of error occurs on that course it will be logged to that file. for now we don't have any switch to disable it but i will add one to avoid logging errors.

the purpose of that file is to log errors if any so that it is easy to proceed with fixing or something.

**Comment by jaan143** [comment]
ok thank you very much
