### ISSUE TITLE
Assistance with 1080 download (Windows)

### ISSUE THREAD

**Issue by scapman2k** [r0oth3x49/udemy-dl#589]
Excuse me if this is not posted in the right place but everything aside from 1080 downloading works.
I have all the required modules installed
Ran pip install ffmpeg-python

I am unsure what to add to the environment variables to enable 1080p downloading

The -q 1080 switch doesn't work, downloading a course without switches will proceed at 720.

This is running on a windows 10 machine. Thank you for your assistance.

**Comment by r0oth3x49** [comment]
@scapman2k -q switch with 1080 will only work if:
 - ffmpeg is installed and path is added windows env.
 - video should have 1080p.
Otherwise udemy-dl will fallback to internal downloading functionality which only works with mp4 (<=720p) videos not streamed one.


By Installing ffmpeg i mean you need to download the exe file for windows from [ffmpeg.org](https://ffmpeg.org/download.html).
This article will help you configure ffmpeg so that udemy-dl can use it. [install-ffmpeg-windows-10](https://windowsloop.com/install-ffmpeg-windows-10/)

Let me know if you still face issue with downloading 1080p and if this information helps you out please do close the issue.
