### ISSUE TITLE
Cloudflare version 2 Captcha challenge

### ISSUE THREAD

**Issue by any0n3** [r0oth3x49/udemy-dl#664]
**cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.**

**To Reproduce**
1. udemy course url: [e.g `https://www.udemy.com/machinelearning/`] '...'
2. Run the following command to reproduce the error.
3. See error

**Expected behavior**

**Screenshots**

**Python Environment (please complete the following information):**
 - OS Platform: [e.g. Windows 10, Ubuntu 16.04, macOS Sierra]
 - Python Version [e.g. 3.x.x]

**Additional context**

**Comment by faldor20** [comment]
This issue is a pretty poor job.. but I also had this problem.
 I guess its possible udemy has just started using Cloudflare.
I was trying to download this course: https://www.udemy.com/course/dr-ks-complete-first-semester-general-chemistry-i-course/
I am on Windows 10 and live in Australia. I've no idea if the location is relevant but it's possible.
I've never tried to download any other courses before, I was already logged in when I tried it, it might be worth testing it after making sure you are logged out of udemy... just trying to think why Cloudflare captcha would be triggering.

**Comment by r0oth3x49** [comment]
I 'm using a third party module/lib and handled the exception simply. the alternative way is to use cookie based auth instead of user/pass
